{"name": "test_two", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n +  where False = hasattr('hello', 'check')", "trace": "self = <test_pytest.test_pytest.TestMyClass object at 0x0000022B568AC4C8>\n\n    def test_two(self):\n        x = \"hello\"\n>       assert hasattr(x, \"check\")\nE       AssertionError: assert False\nE        +  where False = hasattr('hello', 'check')\n\ntest_pytest\\test_pytest.py:80: AssertionError"}, "attachments": [{"name": "stdout", "source": "76361371-879c-4be7-9565-9e9e3db99055-attachment.txt", "type": "text/plain"}], "start": 1583068864574, "stop": 1583068864574, "uuid": "58a0ab13-91f3-40b5-9cc1-a01f0c2ec2a7", "historyId": "8afe24c3debe08db4f2232ad9f364a41", "testCaseId": "3b1b357f1ddfe4f952a75942e4189695", "fullName": "test_pytest.test_pytest.TestMyClass#test_two", "labels": [{"name": "parentSuite", "value": "test_pytest"}, {"name": "suite", "value": "test_pytest"}, {"name": "subSuite", "value": "TestMyClass"}, {"name": "host", "value": "luoluo-PC"}, {"name": "thread", "value": "12128-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_pytest.test_pytest"}]}